### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by cjhelloletsgo** [NoahGWood/OpenEFT#12]
I followed the README but the instructions result in an error.
Replicate by running these commands:
1) git clone --recurse-submodules https://github.com/NoahGWood/OpenEFT.git
2) cd OpenEFT
3) mkdir build
4) cd nbis
Now running commands in "If Linux" section
5) ./setup.sh ../build/

These commands give me this error:
./setup.sh: 396: cd: can't cd to /home/colton/projects/OpenEFT/nbis/an2k/src/lib/an2k
/usr/bin/cp: cannot stat 'select.c.linux': No such file or directory
chmod: cannot access '/home/colton/projects/OpenEFT/nbis/jpeg2k/src/lib/jasper/configure': No such file or directory
chmod: cannot access '/home/colton/projects/OpenEFT/nbis/jpeg2k/src/lib/jasper/aclocal.m4': No such file or directory
chmod: cannot access '/home/colton/projects/OpenEFT/nbis//an2k/src/lib/an2k/select.c': No such file or directory

**Comment by NoahGWood** [comment]
It looks like it didn't pull in the submodule, try going to the root folder and typing
`git submodule update --init` then see if you can build nbis

**Comment by cjhelloletsgo** [comment]
I tried your suggestion but I'm still getting the same error.
![image](https://user-images.githubusercontent.com/70229357/226237732-7c630765-d648-49b3-9278-4fa8ba6a6d3d.png)

**Comment by NoahGWood** [comment]
I was having issues uploading to git, si maybe something got borked there with the submodules.

If the nbis folder is empty, you can try manually downloading it using:
`cd ~/projects/OpenEFT`
`git clone https://github.com/lessandro/nbis.git`
`cd nbis`
`chmod +x setup.sh`
Then run the
`./setup.sh ../build`

**Comment by rtadams89** [comment]
I'm having the same issue and manually pulling in the nbis repository fixes it. It's also interesting that while I see you have a .submodules file, the corresponding nbis folder in the project isn't represented as a submodule. Might be worth deleting the .submodule file and the nbis folder and trying to readd via `git submodule https://github.com/lessandro/nbis.git`
