### ISSUE TITLE
EFT fails ATF validation with data length error

### ISSUE THREAD

**Issue by solarflair** [NoahGWood/OpenEFT#20]
When uploading my EFT file created with OpenEFT to the ATF eforms site, it tells me it cannot be verified and gives the following error:

`Data length too short. Length is 2 must between 3-3 in Field 'T2_HGT' 2.27.1.1 IDC:0`

I've submitted with two different EFTs generated from two different fingerprint cards and I get the same error with both. 

I'm fairly sure that the fingerprints themselves look good (they're not perfect but I work with biometrics professionally so I have some experience with telling a good print from a bad one, and I'd call them adequate). So I'm not sure if this error is saying that I took bad prints or if there's something else wrong with the file generated by OpenEFT.

**Comment by rtadams89** [comment]
I’m not at my computer to verify, but it looks like it’s complaining about the height field. Did you put in your height correctly, including 2 digits for the inches?

**Comment by solarflair** [comment]
> I’m not at my computer to verify, but it looks like it’s complaining about the height field. Did you put in your height correctly, including 2 digits for the inches?

No, it wasn't clear to me what it was expecting (inches or whatever). I assumed feet and inches in a single number based on the "511" that was prefilled as an example, so I put 57 for 5' 7". I'll regenerate it with 507 instead and see if it takes.

**Comment by solarflair** [comment]
The height is what it was. Using 507 instead of 57 resulted in an eft file they accepted. Thanks
