### ISSUE TITLE
NBIS build error

### ISSUE THREAD

**Issue by camtheham** [NoahGWood/OpenEFT#22]
Hello,

I am trying to install on Windows 10 running WSL2 ubuntu 22.04. I installed all of the requirements without issue, and then I tried to install NBIS. I followed the installation guide for linux included in the NBIS directory and did the following:

1. Created a directory named build in the OpenEft directory
2. Ran the setup script with ./setup ../build/ 
3. make config
4. make it
5. make install LIBNBIS=yes

I have also tried LIBNIBS=no and excluding LIBNBIS entirely from the last command. The result I keep getting is shown below. What am I missing? If it helps, I followed the OpenJPEG install guide as well and built into the /home/user_name directory. 

When I manually go into the nbis/ijg/src/lib/jpegb directory, I see that libjpegb.a is actually there. I can even copy this file to the desired destination of ../build/lib. 

Anybody else run into this issue? 

<img width="640" alt="makeInstallError" src="https://github.com/NoahGWood/OpenEFT/assets/24456733/60966f0c-ad05-4165-82a1-e4a0eef8406b">

**Comment by Tim-Healey** [comment]
I am not very familiar with WSL, but maybe try elevating the command?
`sudo make install LIBNBIS=no`
What version of GCC are you using? I could only get the NBIS binaries to install correctly [using an older version](https://github.com/NoahGWood/OpenEFT/discussions/17).

**Comment by Sn1PeR** [comment]
You need to implement this pull request:
https://github.com/lessandro/nbis/pull/1

I built nbis separately, then added the bins to my $PATH and it now works.

**Comment by camtheham** [comment]
@Tim-Healey I am using GCC 9 as I ran into that same issue from that thread and followed the given solution. I forgot to mention that I did try all commands as sudo with the same result, which is what really puzzled me. I will try to build nbis from the link in @Sn1PeR's comment.

**Comment by camtheham** [comment]
Trying to build from that nbis fork still gave me this same error. The second screenshot even shows that the file that "doesn't exist" is exactly where it should be. Any ideas? Maybe I'm missing a package? 

<img width="457" alt="specificError" src="https://github.com/NoahGWood/OpenEFT/assets/24456733/7862f330-7973-4c74-96fb-5958837fa40a">

<img width="1441" alt="libjpeg" src="https://github.com/NoahGWood/OpenEFT/assets/24456733/ec5ef3ca-5a16-4481-a67a-eff882042078">

**Comment by Tim-Healey** [comment]
@camtheham If @Sn1PeR's fix doesn't work, GCC 9 did not work for me either on latest Ubuntu build. I had to downgrade further to 5.

**Comment by camtheham** [comment]
Now I got it to work! Instead of creating my build directory for nbis inside of the main nbis directory, I created it in my /home/user_name directory. Running through the same process as above it worked using this as my build destination. 

Note: I did end up using "sudo make install LIBNBIS=no" this time.
