### ISSUE TITLE
Type-14 Record Field 14.003 / Impression Type (IMP)

### ISSUE THREAD

**Issue by TechT4** [NoahGWood/OpenEFT#35]
Should Type-14 Record Field 14.003 Impression Type (IMP) be set to "0" instead of "1" in the generated EFT file since the prints pulled from the FD-258 that are used in the EFT are the 4 Finger and Thumb plain/flat prints?

Per NIST Special Publication 500-290 Edition 3 (2015) Table 8 "Friction ridge impression types"

0 : Plain Contact - Finger(s) presented on platen or paper without rolling
1 : Rolled Contact - Finger rolled on platen or paper

https://www.nist.gov/publications/data-format-interchange-fingerprint-facial-other-biometric-information-ansinist-itl-1-1

pg. 71  (115)
pg. 359 (403)

**Comment by NoahGWood** [comment]
Hey, sorry I've been super busy with college, but it looks like that should be changed, yes. I'll go ahead and update that right now, unless you want to submit a PR

**Comment by TechT4** [comment]
Hi and thanks for the response. No need for a PR. Thanks again!
