### ISSUE TITLE
ATF eForm 1 Upload Test: Error getting CNT field

### ISSUE THREAD

**Issue by kmenter** [NoahGWood/OpenEFT#8]
I generated an EFT file with no issues. I uploaded it to the eForms website to validate it. I received an error with the CNT field. I started with a high quality jpeg scan and I entered all the prompted fields (the missing fingers prompt, I just hit enter). I ran through the script twice, just to double check. I received the same error.

Have you seen this before? Have you checked the EFT file in the eforms portal?

I wasn't able to get the NIST/an2ktool installed correctly to validate the file myself.

**Comment by NoahGWood** [comment]
Yeah, so the count is off. The latest NIST documentation shows that the type1 record is included in the count, it's apparently not. Also, it looks like the ATF is not actually supporting the FBI standards (which allows for a tenprint card), but thankfully have enough error messages I should be able to brute force my way through this crap

**Comment by kmenter** [comment]
Appreciate the help! I support what the project is trying to do.

**Comment by NoahGWood** [comment]
Fixed in the latest update
