### ISSUE TITLE
Abundance of errors!

### ISSUE THREAD

**Issue by NoahGWood** [NoahGWood/OpenEFT#9]
Additional Error Information:

1. Too many Type 14 Records found. Found 13, need at most 3 

2. Illegal value (code) found Field 'T1_VER' 1.2.1.1 

3. Data length too short. Length is 1 must between 2-2 in Field 'T2_IDC' 2.2.1.1 IDC:0 

4. Illegal characters found: "." in Field 'T2_NAM' 2.18.1.1 IDC:0 

5. Missing mandatory Field 'T2_POB' 2.20 IDC:0 

6. Missing mandatory Field 'T2_SEX' 2.24 IDC:0 

7. Data length too short. Length is 2 must between 3-3 in Field 'T2_HGT' 2.27.1.1 IDC:0 

8. Missing mandatory Field 'T2_HAI' 2.32 IDC:0 

9. Missing mandatory Field 'T14_SEG' 14.21 IDC:1 

10. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:1 

11. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:1 

12. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:1 

13. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:1 

14. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:1 

15. Missing mandatory Field 'T14_SQM' 14.23 IDC:1 

16. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:1 

17. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:1 

18. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:1 

19. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:1 

20. Missing mandatory Field 'T14_AFM' 14.24 IDC:1 

21. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:1 

22. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:1 

23. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:1 

24. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:1 

25. Unsupported Field 14.200.1.1 IDC:1 Field 14.200.1.1 IDC:1 

26. Unsupported Field 14.996.1.1 IDC:1 Field 14.996.1.1 IDC:1 

27. Missing mandatory Field 'T14_SEG' 14.21 IDC:2 

28. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:2 

29. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:2 

30. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:2 

31. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:2 

32. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:2 

33. Missing mandatory Field 'T14_SQM' 14.23 IDC:2 

34. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:2 

35. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:2 

36. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:2 

37. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:2 

38. Missing mandatory Field 'T14_AFM' 14.24 IDC:2 

39. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:2 

40. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:2 

41. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:2 

42. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:2 

43. Unsupported Field 14.200.1.1 IDC:2 Field 14.200.1.1 IDC:2 

44. Unsupported Field 14.996.1.1 IDC:2 Field 14.996.1.1 IDC:2 

45. Missing mandatory Field 'T14_SEG' 14.21 IDC:3 

46. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:3 

47. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:3 

48. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:3 

49. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:3 

50. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:3 

51. Missing mandatory Field 'T14_SQM' 14.23 IDC:3 

52. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:3 

53. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:3 

54. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:3 

55. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:3 

56. Missing mandatory Field 'T14_AFM' 14.24 IDC:3 

57. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:3 

58. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:3 

59. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:3 

60. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:3 

61. Unsupported Field 14.200.1.1 IDC:3 Field 14.200.1.1 IDC:3 

62. Unsupported Field 14.996.1.1 IDC:3 Field 14.996.1.1 IDC:3 

63. Missing mandatory Field 'T14_SEG' 14.21 IDC:4 

64. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:4 

65. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:4 

66. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:4 

67. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:4 

68. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:4 

69. Missing mandatory Field 'T14_SQM' 14.23 IDC:4 

70. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:4 

71. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:4 

72. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:4 

73. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:4 

74. Missing mandatory Field 'T14_AFM' 14.24 IDC:4 

75. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:4 

76. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:4 

77. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:4 

78. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:4 

79. Unsupported Field 14.200.1.1 IDC:4 Field 14.200.1.1 IDC:4 

80. Unsupported Field 14.996.1.1 IDC:4 Field 14.996.1.1 IDC:4 

81. Missing mandatory Field 'T14_SEG' 14.21 IDC:5 

82. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:5 

83. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:5 

84. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:5 

85. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:5 

86. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:5 

87. Missing mandatory Field 'T14_SQM' 14.23 IDC:5 

88. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:5 

89. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:5 

90. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:5 

91. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:5 

92. Missing mandatory Field 'T14_AFM' 14.24 IDC:5 

93. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:5 

94. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:5 

95. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:5 

96. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:5 

97. Unsupported Field 14.200.1.1 IDC:5 Field 14.200.1.1 IDC:5 

98. Unsupported Field 14.996.1.1 IDC:5 Field 14.996.1.1 IDC:5 

99. Missing mandatory Field 'T14_SEG' 14.21 IDC:6 

100. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:6 

101. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:6 

102. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:6 

103. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:6 

104. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:6 

105. Missing mandatory Field 'T14_SQM' 14.23 IDC:6 

106. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:6 

107. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:6 

108. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:6 

109. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:6 

110. Missing mandatory Field 'T14_AFM' 14.24 IDC:6 

111. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:6 

112. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:6 

113. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:6 

114. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:6 

115. Unsupported Field 14.200.1.1 IDC:6 Field 14.200.1.1 IDC:6 

116. Unsupported Field 14.996.1.1 IDC:6 Field 14.996.1.1 IDC:6 

117. Missing mandatory Field 'T14_SEG' 14.21 IDC:7 

118. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:7 

119. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:7 

120. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:7 

121. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:7 

122. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:7 

123. Missing mandatory Field 'T14_SQM' 14.23 IDC:7 

124. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:7 

125. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:7 

126. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:7 

127. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:7 

128. Missing mandatory Field 'T14_AFM' 14.24 IDC:7 

129. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:7 

130. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:7 

131. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:7 

132. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:7 

133. Unsupported Field 14.200.1.1 IDC:7 Field 14.200.1.1 IDC:7 

134. Unsupported Field 14.996.1.1 IDC:7 Field 14.996.1.1 IDC:7 

135. Missing mandatory Field 'T14_SEG' 14.21 IDC:8 

136. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:8 

137. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:8 

138. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:8 

139. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:8 

140. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:8 

141. Missing mandatory Field 'T14_SQM' 14.23 IDC:8 

142. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:8 

143. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:8 

144. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:8 

145. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:8 

146. Missing mandatory Field 'T14_AFM' 14.24 IDC:8 

147. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:8 

148. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:8 

149. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:8 

150. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:8 

151. Unsupported Field 14.200.1.1 IDC:8 Field 14.200.1.1 IDC:8 

152. Unsupported Field 14.996.1.1 IDC:8 Field 14.996.1.1 IDC:8 

153. Missing mandatory Field 'T14_SEG' 14.21 IDC:9 

154. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:9 

155. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:9 

156. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:9 

157. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:9 

158. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:9 

159. Missing mandatory Field 'T14_SQM' 14.23 IDC:9 

160. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:9 

161. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:9 

162. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:9 

163. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:9 

164. Missing mandatory Field 'T14_AFM' 14.24 IDC:9 

165. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:9 

166. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:9 

167. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:9 

168. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:9 

169. Unsupported Field 14.200.1.1 IDC:9 Field 14.200.1.1 IDC:9 

170. Unsupported Field 14.996.1.1 IDC:9 Field 14.996.1.1 IDC:9 

171. Missing mandatory Field 'T14_SEG' 14.21 IDC:10 

172. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:10 

173. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:10 

174. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:10 

175. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:10 

176. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:10 

177. Missing mandatory Field 'T14_SQM' 14.23 IDC:10 

178. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:10 

179. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:10 

180. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:10 

181. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:10 

182. Missing mandatory Field 'T14_AFM' 14.24 IDC:10 

183. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:10 

184. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:10 

185. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:10 

186. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:10 

187. Unsupported Field 14.200.1.1 IDC:10 Field 14.200.1.1 IDC:10 

188. Unsupported Field 14.996.1.1 IDC:10 Field 14.996.1.1 IDC:10 

189. Missing mandatory Field 'T14_SEG' 14.21 IDC:11 

190. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:11 

191. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:11 

192. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:11 

193. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:11 

194. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:11 

195. Missing mandatory Field 'T14_SQM' 14.23 IDC:11 

196. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:11 

197. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:11 

198. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:11 

199. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:11 

200. Missing mandatory Field 'T14_AFM' 14.24 IDC:11 

201. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:11 

202. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:11 

203. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:11 

204. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:11 

205. Unsupported Field 14.200.1.1 IDC:11 Field 14.200.1.1 IDC:11 

206. Unsupported Field 14.996.1.1 IDC:11 Field 14.996.1.1 IDC:11 

207. Missing mandatory Field 'T14_SEG' 14.21 IDC:12 

208. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:12 

209. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:12 

210. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:12 

211. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:12 

212. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:12 

213. Missing mandatory Field 'T14_SQM' 14.23 IDC:12 

214. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:12 

215. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:12 

216. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:12 

217. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:12 

218. Missing mandatory Field 'T14_AFM' 14.24 IDC:12 

219. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:12 

220. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:12 

221. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:12 

222. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:12 

223. Unsupported Field 14.200.1.1 IDC:12 Field 14.200.1.1 IDC:12 

224. Unsupported Field 14.996.1.1 IDC:12 Field 14.996.1.1 IDC:12 

225. Missing mandatory Field 'T14_SEG' 14.21 IDC:13 

226. Missing mandatory Field 'T14_SEG_FGN' 14.21 IDC:13 

227. Missing mandatory Field 'T14_SEG_LFT' 14.21 IDC:13 

228. Missing mandatory Field 'T14_SEG_RGT' 14.21 IDC:13 

229. Missing mandatory Field 'T14_SEG_TOP' 14.21 IDC:13 

230. Missing mandatory Field 'T14_SEG_BTM' 14.21 IDC:13 

231. Missing mandatory Field 'T14_SQM' 14.23 IDC:13 

232. Missing mandatory Field 'T14_SQM_FGN' 14.23 IDC:13 

233. Missing mandatory Field 'T14_SQM_ECOR' 14.23 IDC:13 

234. Missing mandatory Field 'T14_SQM_VID' 14.23 IDC:13 

235. Missing mandatory Field 'T14_SQM_PCOD' 14.23 IDC:13 

236. Missing mandatory Field 'T14_AFM' 14.24 IDC:13 

237. Missing mandatory Field 'T14_AFM_FGP' 14.24 IDC:13 

238. Missing mandatory Field 'T14_AFM_SCO' 14.24 IDC:13 

239. Missing mandatory Field 'T14_AFM_VID' 14.24 IDC:13 

240. Missing mandatory Field 'T14_AFM_PDC' 14.24 IDC:13 

241. Unsupported Field 14.200.1.1 IDC:13 Field 14.200.1.1 IDC:13 

242. Unsupported Field 14.996.1.1 IDC:13 Field 14.996.1.1 IDC:13

**Comment by NoahGWood** [comment]
Okay, so the problem is I was working from the ANSI/NIST 2011 specifications, the FBI 2008 specifications only supports the slap and thumbprint (for some reason).

So, we'll need to remove the extra OCR and records, then process the fingerprints with nfseg and record that information in the type 4. The rest looks like pretty simple fixes, just data santization

**Comment by dillonmabry** [comment]
> Okay, so the problem is I was working from the ANSI/NIST 2011 specifications, the FBI 2008 specifications only supports the slap and thumbprint (for some reason).
> 
> So, we'll need to remove the extra OCR and records, then process the fingerprints with nfseg and record that information in the type 14 record. The rest looks like pretty simple fixes, just data santization and so on

I think this is a great project and am looking forward to seeing what you guys can do with it. We need an open source way to work with .EFTs and for people like myself who have existing printed copies of fingerprints who want to be able to convert to .EFT.

**Comment by NoahGWood** [comment]
Fixed, works just fine with ATF's portal now.
Pretty large merge coming in...
